import { StyleSheet } from 'react-native';

import { DesignColorPalette, Radius, Spacing, Typography } from '@/constants/design';
import { MaxContentWidth } from '@/constants/theme';

export function createStaffStyles(DesignColors: DesignColorPalette) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: DesignColors.canvas,
    },
    content: {
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.section,
      gap: Spacing.lg,
      width: '100%',
      maxWidth: MaxContentWidth,
      alignSelf: 'center',
    },
    header: {
      gap: Spacing.xs,
    },
    eyebrow: {
      ...Typography.eyebrow,
      textTransform: 'uppercase',
      color: DesignColors.inkSubtle,
      letterSpacing: 1.2,
      fontSize: 11,
    },
    title: {
      ...Typography.pageTitle,
      color: DesignColors.ink,
      fontWeight: '600',
    },
    subtitle: {
      ...Typography.body,
      color: DesignColors.inkMuted,
      lineHeight: 22,
    },
    hint: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
      lineHeight: 18,
    },
    card: {
      backgroundColor: DesignColors.surface1,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      padding: Spacing.lg,
      gap: Spacing.md,
    },
    cardElevated: {
      backgroundColor: DesignColors.surface1,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: DesignColors.hairlineStrong,
      padding: Spacing.lg,
      gap: Spacing.md,
      shadowColor: DesignColors.accentViolet,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 4,
    },
    scanCtaButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(139,92,246,0.45)',
      backgroundColor: 'rgba(139,92,246,0.14)',
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      minHeight: 48,
      shadowColor: DesignColors.accentViolet,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 4,
    },
    scanCtaButtonPressed: {
      opacity: 0.88,
      transform: [{ scale: 0.985 }],
    },
    scanCtaButtonText: {
      ...Typography.button,
      color: DesignColors.ink,
      fontWeight: '700',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    searchRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      alignItems: 'stretch',
    },
    searchInput: {
      flex: 1,
    },
    fieldLabel: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      fontSize: 11,
      marginBottom: -4,
    },
    actionRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    actionRowItem: {
      flex: 1,
    },
    fullWidthButton: {
      width: '100%',
    },
    buttonPressed: {
      opacity: 0.88,
    },
    sessionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    linkText: {
      ...Typography.caption,
      color: DesignColors.accentSky,
      fontWeight: '600',
    },
    sessionPlate: {
      ...Typography.cardTitle,
      color: DesignColors.ink,
      fontWeight: '600',
    },
    sessionDetail: {
      ...Typography.bodySm,
      color: DesignColors.inkMuted,
    },
    scannerLoading: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(11,15,25,0.6)',
      zIndex: 100,
    },
    vehicleFoundCard: {
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(16,185,129,0.35)',
      backgroundColor: 'rgba(16,185,129,0.08)',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      gap: 2,
    },
    metricRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    metricBadge: {
      flex: 1,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface2,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.sm,
      alignItems: 'center',
      gap: 4,
    },
    metricBadgeAvailable: {
      borderColor: 'rgba(16,185,129,0.35)',
      backgroundColor: 'rgba(16,185,129,0.08)',
    },
    metricBadgeInUse: {
      borderColor: 'rgba(245,158,11,0.35)',
      backgroundColor: 'rgba(245,158,11,0.08)',
    },
    metricBadgeTotal: {
      borderColor: 'rgba(96,165,250,0.3)',
      backgroundColor: 'rgba(96,165,250,0.08)',
    },
    metricLabel: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      fontSize: 10,
    },
    metricValue: {
      ...Typography.metricValue,
    },
    metricValueAvailable: {
      color: DesignColors.accentEmerald,
    },
    metricValueInUse: {
      color: DesignColors.accentAmber,
    },
    metricValueTotal: {
      color: DesignColors.accentSky,
    },
    slotGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
    },
    slotChip: {
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: DesignColors.hairlineStrong,
      backgroundColor: DesignColors.surface3,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.xs,
    },
    slotChipSelected: {
      borderColor: DesignColors.accentViolet,
      backgroundColor: 'rgba(139,92,246,0.12)',
      shadowColor: DesignColors.accentViolet,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 3,
    },
    slotChipPressed: {
      opacity: 0.85,
    },
    slotChipText: {
      ...Typography.bodySm,
      color: DesignColors.inkMuted,
      fontWeight: '500',
    },
    slotChipTextSelected: {
      color: DesignColors.ink,
      fontWeight: '600',
    },
    floorRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: DesignColors.hairline,
      paddingTop: Spacing.xs,
    },
    floorName: {
      ...Typography.bodySm,
      color: DesignColors.ink,
    },
    floorStats: {
      ...Typography.caption,
      color: DesignColors.inkMuted,
    },
    quickGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
    },
    quickItem: {
      flexBasis: '47%',
      flexGrow: 1,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface2,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      alignItems: 'center',
    },
    quickText: {
      ...Typography.bodySm,
      color: DesignColors.ink,
      fontWeight: '500',
      textAlign: 'center',
    },
    sessionList: {
      gap: Spacing.sm,
    },
    sessionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.sm,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface2,
      padding: Spacing.md,
    },
    sessionRowLeft: {
      flex: 1,
      gap: 2,
    },
    sessionRowId: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
      fontFamily: Typography.mono.fontFamily,
    },
    sessionRowPlate: {
      ...Typography.bodySm,
      fontWeight: '600',
      color: DesignColors.ink,
      letterSpacing: 0.4,
    },
    sessionRowSlot: {
      ...Typography.caption,
      color: DesignColors.inkMuted,
    },
    sessionRowRight: {
      alignItems: 'flex-end',
      gap: Spacing.xs,
      justifyContent: 'center',
    },
    statusBadgeActive: {
      borderRadius: Radius.pill,
      backgroundColor: 'rgba(16,185,129,0.12)',
      borderWidth: 1,
      borderColor: 'rgba(16,185,129,0.35)',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 3,
    },
    statusBadgeTextActive: {
      ...Typography.caption,
      color: DesignColors.accentEmerald,
      textTransform: 'uppercase',
      fontWeight: '600',
      fontSize: 10,
      letterSpacing: 0.5,
    },
    sessionRowDuration: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
    },
    navCard: {
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface2,
      padding: Spacing.md,
      gap: 4,
    },
    navCardPressed: {
      opacity: 0.85,
      backgroundColor: DesignColors.surface3,
    },
    navCardTitle: {
      ...Typography.bodySm,
      fontWeight: '600',
      color: DesignColors.ink,
    },
    navCardMeta: {
      ...Typography.caption,
      color: DesignColors.inkMuted,
    },
    settingsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface1,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.md,
    },
    settingsButtonText: {
      ...Typography.button,
      color: DesignColors.ink,
      flex: 1,
    },
    profileName: {
      ...Typography.cardTitle,
      color: DesignColors.ink,
      fontWeight: '600',
    },
    profileMeta: {
      ...Typography.bodySm,
      color: DesignColors.inkMuted,
    },
    slotStatusAvailable: {
      backgroundColor: 'rgba(16,185,129,0.06)',
      borderColor: 'rgba(16,185,129,0.4)',
      shadowColor: DesignColors.accentEmerald,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 2,
    },
    slotStatusInUse: {
      backgroundColor: 'rgba(245,158,11,0.10)',
      borderColor: 'rgba(245,158,11,0.45)',
    },
    slotStatusUnavailable: {
      backgroundColor: DesignColors.surface3,
      borderColor: DesignColors.hairline,
    },
    slotCell: {
      width: '30%',
      aspectRatio: 1,
      borderRadius: Radius.lg,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    slotCellInner: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    slotCellText: {
      ...Typography.bodySm,
      color: DesignColors.ink,
      fontWeight: '600',
      letterSpacing: 0.3,
    },
    slotCellTextInUse: {
      color: DesignColors.accentAmber,
    },
    slotCellTextUnavailable: {
      color: DesignColors.inkSubtle,
    },
    slotHeroHeader: {
      minHeight: 168,
      borderRadius: Radius.xl,
      borderWidth: 1,
      padding: Spacing.lg,
      justifyContent: 'flex-end',
      gap: Spacing.xs,
      overflow: 'hidden',
    },
    slotHeroHeaderAvailable: {
      backgroundColor: 'rgba(16,185,129,0.08)',
      borderColor: 'rgba(16,185,129,0.4)',
    },
    slotHeroHeaderInUse: {
      backgroundColor: DesignColors.surface2,
      borderColor: DesignColors.hairlineStrong,
      opacity: 0.7,
    },
    slotHeroHeaderUnavailable: {
      backgroundColor: DesignColors.surface2,
      borderColor: DesignColors.hairline,
      opacity: 0.45,
    },
    slotHeroEyebrow: {
      ...Typography.eyebrow,
      color: DesignColors.inkSubtle,
      textTransform: 'uppercase',
      fontSize: 11,
    },
    slotHeroTitle: {
      ...Typography.headline,
      color: DesignColors.ink,
      fontWeight: '700',
    },
    slotHeroStatus: {
      ...Typography.caption,
      textTransform: 'uppercase',
      fontWeight: '600',
      letterSpacing: 0.8,
    },
    slotHeroStatusAvailable: {
      color: DesignColors.accentEmerald,
    },
    slotHeroStatusInUse: {
      color: DesignColors.inkMuted,
    },
    slotHeroStatusUnavailable: {
      color: DesignColors.inkSubtle,
    },
    slotHeroHidden: {
      opacity: 0,
    },
    slotHeroFill: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    slotPressable: {
      width: '30%',
      aspectRatio: 1,
    },
    slotPressablePressed: {
      opacity: 0.92,
      transform: [{ scale: 0.97 }],
    },
    floorPanel: {
      gap: Spacing.md,
    },
    floorTabs: {
      flexDirection: 'row',
      gap: Spacing.xs,
      paddingVertical: 2,
    },
    floorTab: {
      minWidth: 52,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface2,
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.sm,
      alignItems: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    floorTabBadge: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
      fontSize: 10,
      fontWeight: '600',
      minWidth: 18,
      textAlign: 'center',
      borderRadius: Radius.pill,
      overflow: 'hidden',
      paddingHorizontal: 5,
      paddingVertical: 1,
      backgroundColor: DesignColors.surface3,
    },
    floorTabBadgeActive: {
      ...Typography.caption,
      color: DesignColors.accentViolet,
      fontSize: 10,
      fontWeight: '700',
      minWidth: 18,
      textAlign: 'center',
      borderRadius: Radius.pill,
      overflow: 'hidden',
      paddingHorizontal: 5,
      paddingVertical: 1,
      backgroundColor: 'rgba(139,92,246,0.2)',
    },
    floorTabActive: {
      borderColor: DesignColors.accentViolet,
      backgroundColor: 'rgba(139,92,246,0.12)',
    },
    floorTabPressed: {
      opacity: 0.88,
    },
    floorTabText: {
      ...Typography.button,
      color: DesignColors.inkSubtle,
      fontSize: 13,
    },
    floorTabTextActive: {
      ...Typography.button,
      color: DesignColors.ink,
      fontWeight: '600',
      fontSize: 13,
    },
    floorMeta: {
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface2,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      gap: 4,
    },
    floorMetaTitle: {
      ...Typography.bodySm,
      color: DesignColors.ink,
      fontWeight: '600',
    },
    floorMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    floorMetaStats: {
      ...Typography.caption,
      color: DesignColors.accentEmerald,
      fontWeight: '600',
    },
    floorMetaStatsMuted: {
      ...Typography.caption,
      color: DesignColors.inkMuted,
    },
    floorMetaSub: {
      ...Typography.caption,
      color: DesignColors.inkMuted,
    },
    legendRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.md,
    },
    legendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    legendDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    legendText: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
      fontSize: 11,
    },
    slotPickerPanel: {
      gap: Spacing.sm,
    },
    slotPickerMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: DesignColors.hairline,
      backgroundColor: DesignColors.surface2,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
    },
    slotPickerMetaText: {
      ...Typography.caption,
      color: DesignColors.accentEmerald,
      fontWeight: '600',
    },
    slotPickerMetaMuted: {
      ...Typography.caption,
      color: DesignColors.inkSubtle,
      fontSize: 11,
    },
    compactSlotGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
    },
    compactSlotCell: {
      width: '18.5%',
      minWidth: 52,
      aspectRatio: 1.05,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: DesignColors.hairlineStrong,
      backgroundColor: DesignColors.surface3,
      alignItems: 'center',
      justifyContent: 'center',
    },
    compactSlotCellSelected: {
      borderColor: DesignColors.accentViolet,
      backgroundColor: 'rgba(139,92,246,0.18)',
      shadowColor: DesignColors.accentViolet,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.45,
      shadowRadius: 10,
      elevation: 4,
    },
    compactSlotCellPressed: {
      opacity: 0.88,
      transform: [{ scale: 0.96 }],
    },
    compactSlotCellText: {
      ...Typography.caption,
      color: DesignColors.inkMuted,
      fontWeight: '600',
      fontSize: 11,
      letterSpacing: 0.2,
    },
    compactSlotCellTextSelected: {
      color: DesignColors.ink,
      fontWeight: '700',
    },
  });
}

export type StaffStyles = ReturnType<typeof createStaffStyles>;
